### ISSUE TITLE
Unnecessary redirect to '/' on logout with angular-sdk 

### ISSUE THREAD

**Issue by stevebread** [stormpath/express-stormpath#126]
A logout request via the angular-sdk is redirected to '/' which returns the entire index.html. This is unnecessary for an AJAX logout.

**Comment by typerandom** [comment]
Closing since this is already supported in the the library. See:
https://github.com/stormpath/express-stormpath/blob/master/lib/controllers/logout.js#L21

I.e. this is a bug that is in the Stormpath Angular integration and that has been fixed in this PR:
https://github.com/stormpath/stormpath-sdk-angularjs/pull/48/files#diff-47b4b61d2e1468e55e538bcad7da0d1eR134

Unfortunately not merged in yet. But once it is, it will work as expected there.

**Comment by typerandom** [comment]
Created a new issue so that we can track this in the Angular SDK.

https://github.com/stormpath/stormpath-sdk-angularjs/issues/69
