### ISSUE TITLE
Remove Fields by Default

### ISSUE THREAD

**Issue by rdegges** [stormpath/express-stormpath#183]
If you have the `website: true` option enabled, and nothing else, the registration page looks like this:

<img width="1280" alt="screenshot 2015-11-02 10 36 08" src="https://cloud.githubusercontent.com/assets/90247/10890590/9fbfaec8-814d-11e5-8eb8-41283820b0de.png">

As you can see, there are lots of fields there. Previously, we only showed the:

- first name
- last name
- email
- password

Fields, which is what we should return to doing. This way users (by default) aren't overwhelmed with all of the fields available.

**Comment by typerandom** [comment]
It seems like these extra fields were introduced in August in order to comply with the integration spec:
https://github.com/stormpath/stormpath-sdk-node/commit/b2eebf3f4bb31ab299a04bba1aab67d451fc03ef

I.e. since there is no filtering on the registration fields, it just meant that they were added to the view:
https://github.com/stormpath/express-stormpath/blob/master/lib/views/register.jade#L27

My suggestion is to simply add a enabled flag to each field, and that way we'll be able to set which fields to show default, and if the user wants to add anything else, he can just change those values.

My only concern is that there are users that have been using the old way of hiding/showing fields, and for them this might suddenly mean that the fields that they want to show are suddenly not showing.

@rdegges @robertjd What do you think?

**Comment by robertjd** [comment]
We should make a PR on the framework spec repo, modifying the registration configuration to only enable the four fields that we want.
