### ISSUE TITLE
stormpath.apiAuthenticationRequired not checking with Stormpath whether token was revoked?

### ISSUE THREAD

**Issue by oekekezie** [stormpath/express-stormpath#261]
I'm using OAuth2 password grant type. To recreate the bug... (1) Generate a token. (2) Issue a DELETE request to the stormpath_access_token_href and get back a 204 response. (3) Issue a POST request to an endpoint on my server that's secured by stormpath.apiAuthenticationRequired including the previously revoked token. I'm still able to pass stormpath.apiAuthenticationRequired.

My understanding was that stormpath.apiAuthenticationRequired checks with Stormpath to see if the token has been revoked by default? Or is this expected behavior?

**Comment by timothyej** [comment]
This is not the expected behavior. It should revalidate the token against Stormpath unless you've turned it off: <https://docs.stormpath.com/nodejs/express/latest/authentication.html?highlight=local#token-validation-strategy>

Could you verify your configuration to ensure that the `validationStrategy` is not set to `'local'`?

**Comment by oekekezie** [comment]
I'm not setting the validation strategy so it should be "stormpath" by default according to the documents and config.yml. That being said, it still does not work even when I specify "stormpath" as the validation strategy.

```javascript
app.use(
	bodyParser.json(),
	bodyParser.urlencoded({
		extended: true
	}),
	stormpath.init(app, {
		website: false,
		web: {
	    oauth2: {
	      password: {
	        validationStrategy: 'stormpath'
	      }
	    }
	  }
	}),
	require('./routers')
);
```

Any thoughts?

**Comment by oekekezie** [comment]
I ended up just using the REST API to validate my tokens and to check for group membership.

**Comment by schamp** [comment]
I am experiencing the same thing.  

first, looking at the source code, it appears that the validationStrategy === local check only occurs when getUser() is called, and only if the request passes the access token via a cookie, not a Bearer header.  If using a bearer header, it just calls "application.authenticateApiRequest".

Note that this appears to be a separate middleware hook from stormpath_express.apiAuthenticationRequired middleware.  It appears that the apiAuthenticationRequired does not check the config object, it just passes the request through to application.authenticateApiRequest(...) -- see api-authentication-required.js:61

In either case (from getUser() or authenticateApiRequest()), it just calls application.authenticateApiRequest(...).
This appears to ultimately pass the token in through to the OauthAccessTokenAuthenticator.js:authenticate(...) function.  This function tries to get the account and then creates an authentication result, but I don't see that it ever attempts to validate that the oauth token has not been revoked.

It looks like (in stormpath:jwt-authenticator.js:69) that remote validation is not implemented for JWTs in the stormpath SDK.  In fact, it appears that authenticateApiRequest is intended to be deprecated ( see https://github.com/stormpath/stormpath-sdk-node/issues/357 )

There's probably more to it than this (I have only spent the last hour or so digging into it), but checking for revoked access tokens is something I would very much like to have working in the stormpath-express middleware.

**Comment by robertjd** [comment]
Hello everyone, I will be looking into this issue tomorrow.

**Comment by robertjd** [comment]
Thanks @schamp for looking into this!  You're exactly right, the problem happens because are using the `application.authenticateApiRequest()` method for authentication our password-grant tokens, but that method was originally designed for the client-credential tokens and as such it isn't working quite right.

We're about to release a 3.0 version of this library on Monday.  We probably don't have time to fix this before then, but we'll work on it soon after as a 3.0.1 release.  Stay tuned!

**Comment by schamp** [comment]
Thanks @robertjd , I wait with bated breath.
