### ISSUE TITLE
Remove all cookies in session

### ISSUE THREAD

**Issue by tungpham** [stormpath/express-stormpath#373]
Looks like when a POST is made to /logout, only the accessToken and refreshToken cookies are deleted. It should delete every other cookies. This will make express-stormpath works with express-session in session management

**Comment by robertjd** [comment]
Thanks for the report, are the specific cookies that are causing a conflict?

**Comment by tungpham** [comment]
express-session will create a connect.sid cookie. After /logout, that cookie still remain there. express-stormpath only clear out its own cookies (accessToken and refreshToken). The doc makes it sounds like all session cookies will be cleared.

https://docs.stormpath.com/nodejs/express/latest/logout.html#configuration-options

**Comment by robertjd** [comment]
Thanks for the info!  I see how our documentation could make it seem that we delete all cookies.  However we don't want to touch any cookies other than our own, as someone may use the connect session for other purposes.  But we do want to make it easy for you to hook into our logout process, so that you can delete the connect session if needed.  We have this tracked in #218 and we've opened that task for this week.  Please follow that issue for updates.  Thanks again!
