### ISSUE TITLE
Social logins are not being redirected properly

### ISSUE THREAD

**Issue by mdeggies** [stormpath/express-stormpath#482]
Issue reported by one of our users:

**When a user navigates to an internal page on my site, but is not logged in, I expect him to be taken to the login page and then be redirected to the originally-requested internal page upon successful login.**

It looks like this is also the intention of the Stormpath code, but it is not working.

I logout. 
I navigate to an internal page. I'm redirected to https://localhost/api/v1/sdriver/login?next=%2Fapi%2Fv1%2Fdriver%2F

Looks good. I'm taken to the login page and there is a next param pointing to the desired target.

I then do a **social login**, via the Google button on my login page. 
**After login, I'm taken to my Stormpath web.login.nextUri page, and not to the desired target**.

Looking at the express-stormpath code, it appears that it is trying to handle this case: 
https://github.com/stormpath/express-stormpath/blob/master/lib/controllers/google-login.js#L67 checks first for query.next, and only then for nextUri.

But, problem. By the time the code gets there, it has lost the next field.

```
req.url is:"/callbacks/google?code=4/Je1WzWBbiKTkDHwsM6Bv0vyVc9W2ClPVVPMajZrU8uo&scope=https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.profile"
```

and req.query only holds: 

```
{ 
code: "4/Je1WzWBbiKTkDHwsM6Bv0vyVc9W2ClPVVPMajZrU8uo", 
scope: "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile" 
}
```

I don't know if this is a general bug, or not supported yet, or caused by some interaction with my nginx-proxied config, or some interaction with my use of social-login unification (copied from https://github.com/stormpath/stormpath-express-social-unification-example)

**Comment by typerandom** [comment]
This is definitely something that isn't supported yet. The question is what the best way is to support this.

One solution is to append the `next` parameter onto the callback URI (cleanest solution). But the issue here is that the URI to redirect back to could be any URI, and it would have to be white listed as a callback in the OAuth provider. So that makes it out of question.

The other solution is to create a cookie, save the redirect URI, then when we're redirected back, read the `next` URI from the cookie and redirect to that URI.

In order to avoid tampering/weird behaviour, we could sign the cookie, set a TTL, and always clear/set the cookie when we login with a social provider.

It's a bit hacky. But since we don't have any better way to store that state. It's probably the best solution.

@robertjd What do you think?

**Comment by robertjd** [comment]
Correct, the cookie approach will be needed here.  And I agree that we should sign it, and we should remove it when the user returns from the provider.  We should do this to our existing oauth state token, if we're not already.

@mdeggies I understand that you're referring to a dynamic redirect, but can you also check the static redirect for us?  E.g. if you configure `web.login.nextUri`, are you redirect to that URI in that case?  Thanks!
